# Generated by Django 3.2.7 on 2022-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('Marital_status', models.CharField(max_length=100)),
                ('Sleep', models.CharField(max_length=100)),
                ('Depression', models.CharField(max_length=100)),
                ('Smoking', models.CharField(max_length=100)),
                ('Diabetes', models.CharField(max_length=100)),
                ('BP', models.CharField(max_length=100)),
                ('Hypersensitivity', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=100)),
                ('trestbps', models.CharField(max_length=100)),
                ('chol', models.CharField(max_length=100)),
                ('fbs', models.CharField(max_length=100)),
                ('restecg', models.CharField(max_length=100)),
                ('thalach', models.CharField(max_length=100)),
                ('exang', models.CharField(max_length=100)),
                ('oldpeak', models.CharField(max_length=100)),
                ('slope', models.CharField(max_length=100)),
                ('ca', models.CharField(max_length=100)),
                ('thal', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
