# Generated by Django 3.2.7 on 2022-10-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPredictModel',
            new_name='UserPredictDataModel',
        ),
    ]
